name: pull_request_test

on:
    pull_request:
        branches: [development]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 18

            - name: Cache Node.js modules
              id: cache-node-modules
              uses: actions/cache@v2
              with:
                  path: node_modules
                  key: node-modules-${{ runner.os }}-${{ hashFiles('**/package.json') }}
                  restore-keys: |
                      node-modules-${{ runner.os }}-

            - name: Install Dependencies
              if: steps.cache-node-modules.outputs.cache-hit != 'true'
              run: npm install

            - name: Run Tests
              run: npm test

            - name: Save cache
              if: steps.cache-node-modules.outputs.cache-hit != 'true'
              run: echo "Cache updated"
