name: reviewdog
on:
    pull_request:
        branches: ['development']
jobs:
    eslint:
        name: runner / eslint
        runs-on: ubuntu-latest
        permissions:
            contents: read
            pull-requests: write
        steps:
            - uses: actions/checkout@v3
            - uses: reviewdog/action-eslint@v1
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  reporter: github-pr-review 
                  eslint_flags: '.'
                  level: error
                  fail_on_error: true
